### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by UsuarioIncognito** [SistemasTecTlaxiaco/infografia-UsuarioIncognito#1]
[SN_Bautista_Sanjuan_Adal_Eliel_1AS.pdf](https://github.com/user-attachments/files/16841703/SN_Bautista_Sanjuan_Adal_Eliel_1AS.pdf)

**Comment by irwingsael** [comment]
redacción y ortografía : 14/14
exposición de ideas centrales : 16/16
organización de ideas centrales : 14/14
uso de imágenes y colores : 14/14
presentación visual : 14/14
referencias : 13/14
presentación : 14/14
calificación final : 19/20

**Comment by josealfredo79** [comment]
bien hecho y revisado..
